#!/usr/bin/python

# 上传文件到七牛云
# 依赖：python 3

import os
import sys
import fileinput

from qiniu import Auth, put_file, etag
from qiniu import CdnManager


def upload_file(localfile, filename):
    '''
    @param localfile 本地文件
    @param filename CDN 保存的文件名
    '''
    # config
    access_key = 'ACCESS KEY'
    secret_key = 'SECRET KEY'
    bucket_name = 'BUCKET NAME'
    base_url = 'https://img.static.olakeji.com'

    q = Auth(access_key, secret_key)
    token = q.upload_token(bucket_name, filename, 3600)
    ret, info = put_file(token, filename, localfile)
    if ret['key'] != filename:
        print('{} 上传 CDN 失败. ret: {}, info: {}'.format(filename, ret, info))
        sys.exit(1)

    # 刷新 CDN 文件
    cdn_manager = CdnManager(q)
    urls = [
        base_url + '/' + filename,
    ]
    refresh_url_result = cdn_manager.refresh_urls(urls)
    if refresh_url_result[0]['error'] != 'success':
        print("刷新 CDN 失败. 返回: {}".format(refresh_url_result))
        sys.exit(1)
    print("{} 上传 CDN 并刷新成功.".format(localfile))


def get_files():
    for line in sys.stdin:
        oldrev, newrev, refname = tuple(line.split())
        git_cmd = 'git diff --name-only {} {}'.format(oldrev, newrev)
        res = os.popen(git_cmd).read()
        files = filter(is_valid_js_file, res.split('\n'))
    return files


def is_valid_js_file(file):
    return os.path.splitext(file)[1] == '.js'


def get_desc_filename(file):
    return os.path.basename(file)


def main():
    files = get_files()
    for localfile in files:
        filename = get_desc_filename(localfile)
        upload_file(localfile, filename)


if __name__ == '__main__':
    main()
    sys.exit(0)
